<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class QuickEmailSettings {
	private $quick_email_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'quick_email_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'quick_email_settings_page_init' ) );
	}

	public function quick_email_settings_add_plugin_page() {
		add_submenu_page(
			'QuickEmail_plugin', // Top level slug
			'Quick Email Settings', // Page title
			'Settings', // menu_title
			'manage_options', // capability
			'quick_email-settings', // menu_slug
			array( $this, 'quick_email_settings_create_admin_page' ), // function
			2 // position
		);
	}

	public function quick_email_settings_create_admin_page() {
		$this->quick_email_settings_options = get_option( 'quick_email_settings_option_name' ); ?>

		<div class="wrap">
			<h2>Quick Email Settings</h2>
			<p style="margin-right:30%">All emails from this plugin will be sent to the admin email address listed below. For additional addresses, please use a comma separator.<br><i>(Example: admin@email.com,sales@email.com,marketing@email.com)</i></p>
			<p style="margin-right:30%"><strong>[application_form]</strong> and <strong>[contact_form]</strong> shortcode should be used to display the forms respectively.</p>
			<p style="margin-right:30%"><strong>Important Notes:</strong></p>
			<ul>
				<li>The shortcode handles posting the entry to the database, so leave out <i>action=""</i> in the form tag</li>
				<li>A hidden form field with name and id 'contact_check' can be used as a honeypot.</li>
				<li>To automate email sending, set up a cronjob to run <i>php /your-website-root/wp-content/plugins/quick-email/templates/admin.php</i> every 5 minutes or so.</li>
			</ul>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'quick_email_settings_option_group' );
					do_settings_sections( 'quick-email-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function quick_email_settings_page_init() {
		register_setting(
			'quick_email_settings_option_group', // option_group
			'quick_email_settings_option_name', // option_name
			array( $this, 'quick_email_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'quick_email_settings_setting_section', // id
			'', // title
			array( $this, 'quick_email_settings_section_info' ), // callback
			'quick-email-settings-admin' // page
		);

		add_settings_field(
			'admin_email_0', // id
			'Receiver Email', // title
			array( $this, 'admin_email_0_callback' ), // callback
			'quick-email-settings-admin', // page
			'quick_email_settings_setting_section' // section
		);

		add_settings_field(
			'admin_email_1', // id
			'Sender Email', // title
			array( $this, 'admin_email_1_callback' ), // callback
			'quick-email-settings-admin', // page
			'quick_email_settings_setting_section' // section
		);

		add_settings_field(
			'form_code_1', // id
			'Application Form', // title
			array( $this, 'form_code_1_callback' ), // callback
			'quick-email-settings-admin', // page
			'quick_email_settings_setting_section' // section
		);

		add_settings_field(
			'form_code_2', // id
			'Contact Form', // title
			array( $this, 'form_code_2_callback' ), // callback
			'quick-email-settings-admin', // page
			'quick_email_settings_setting_section' // section
		);

	}

	public function quick_email_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['admin_email_0'] ) ) {
			$sanitary_values['admin_email_0'] = sanitize_text_field( $input['admin_email_0'] );
		}

		if ( isset( $input['admin_email_1'] ) ) {
			$sanitary_values['admin_email_1'] = sanitize_text_field( $input['admin_email_1'] );
		}

		if ( isset( $input['form_code_1'] ) ) {
			$sanitary_values['form_code_1'] = $input['form_code_1'];
		}

		if ( isset( $input['form_code_2'] ) ) {
			$sanitary_values['form_code_2'] = $input['form_code_2'];
		}

		return $sanitary_values;
	}

	public function quick_email_settings_section_info() {
		
	}

	public function admin_email_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="quick_email_settings_option_name[admin_email_0]" id="admin_email_0" value="%s">',
			isset( $this->quick_email_settings_options['admin_email_0'] ) ? esc_attr( $this->quick_email_settings_options['admin_email_0']) : ''
		);
	}

	public function admin_email_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="quick_email_settings_option_name[admin_email_1]" id="admin_email_1" value="%s">',
			isset( $this->quick_email_settings_options['admin_email_1'] ) ? esc_attr( $this->quick_email_settings_options['admin_email_1']) : ''
		);
	}

	public function form_code_1_callback() {
		printf(
			'<textarea class="large-text" rows="20" name="quick_email_settings_option_name[form_code_1]" id="form_code_1">%s</textarea>',
			isset( $this->quick_email_settings_options['form_code_1'] ) ? esc_attr( $this->quick_email_settings_options['form_code_1']) : ''
		);
	}

	public function form_code_2_callback() {
		printf(
			'<textarea class="large-text" rows="20" name="quick_email_settings_option_name[form_code_2]" id="form_code_2">%s</textarea>',
			isset( $this->quick_email_settings_options['form_code_2'] ) ? esc_attr( $this->quick_email_settings_options['form_code_2']) : ''
		);
	}

}
if ( is_admin() )
	$quick_email_settings = new QuickEmailSettings();

/* 
 * Retrieve this value with:
 * $quick_email_settings_options = get_option( 'quick_email_settings_option_name' ); // Array of All Options
 * $admin_email_0 = $quick_email_settings_options['admin_email_0']; // Admin Email Address
 * $admin_email_0 = $quick_email_settings_options['admin_email_1']; // Admin Email Address
 * $form_code_1 = $quick_email_settings_options['form_code_1']; // Form Code
 * $form_code_2 = $quick_email_settings_options['form_code_2']; // Form Code
 */
